id: I6EF7A4F7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T09:54:27+00:00'
last_modified: '2022-06-08T06:37:43.201749+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16133
  title: དྲང་ངེས་ལེགས་བཤད་སྙིང་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B644:
      image_group_id: I1KG16137
      title: ''
      total_pages: 346
      order: 1
      base_file: B644.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
